# Generated by Django 4.2.7 on 2023-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_stunetinfo_delete_table_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stunetinfo',
            name='Code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stunetinfo',
            name='Roll',
            field=models.IntegerField(),
        ),
    ]
