# Generated by Django 4.2.7 on 2023-11-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=20)),
                ('s_roll', models.IntegerField()),
                ('s_dep', models.CharField(max_length=3)),
            ],
        ),
    ]
